version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gs-app-composer-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q9pqp4mwgjy7"
s3_prefix = "gs-app-composer-api"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
